model: 
  type : 'DGD'
  n_mels : 40
  dropout : 0.2
  label: 1
  input : "d_dd"
---
train:
  epoch: 200
  nframe : 600
  batch_size: 128
  num_workers: 8
  summary_interval: 10
---
loss:
  type: 'BCELoss' 
---
optim:
  type: "Adam" # Adam
  Adam: 0.001
  Adabound:
    initial: 0.001
    final: 0.05
---
scheduler: 
  type: 'Plateau' # Plateau, oneCycle, None
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio:
  shift : 128
  frame : 512
  samplerate : 16000
---
data:
  root: '/home/data/kbh/VADK/AVTR/mel40/'
---
log:
  root: '/home/nas/user/kbh/VADK/'
