model:
  feature_size : 512
---
train:
  epoch: 50
  batch_size: 64 
  num_workers: 16 
  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'MSE' 
---
optim:
  type: "Adam" # Adam
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
---
scheduler: 
  type: 'Plateau' # Plateau, oneCycle, None
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio:
  frame : 1024
  shift : 256
  samplerate : 16000
---
data:
  SNR :  ['SNR-7','SNR-5','SNR0','SNR5','SNR7','SNR10']
  root: '/home/data/kbh/MCFE/CGMM_RLS_MPDR/mel-40/'
---
log:
  root: '/home/nas/user/kbh/VADK/'
